export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_ERROR = 'USER_DETAILS_ERROR'

export const ALL_USER_DETAILS_REQUEST = 'ALL_USER_DETAILS_REQUEST'
export const ALL_USER_DETAILS_SUCCESS = 'ALL_USER_DETAILS_SUCCESS'
export const ALL_USER_DETAILS_ERROR = 'ALL_USER_DETAILS_ERROR'
