export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const FETCH_CART_ITEMS_DATA = "FETCH_CART_ITEMS_DATA";
export const CART_ITEMS_REMOVE = "CART_ITEMS_REMOVE";
export const CART_ITEMS_ERROR = "CART_ITEMS_ERROR";
